// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5uNYNFEavah2Vz6NVjQdjEekBS3KAU8c',
    appId: '1:695848555081:android:eb04b64085c6d8eacfa598',
    messagingSenderId: '695848555081',
    projectId: 'group-money-management-app',
    storageBucket: 'group-money-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLUcelBFR6fbaLXOyGL8t-FhfdGTzvJQ',
    appId: '1:695848555081:ios:97211f408de3f195cfa598',
    messagingSenderId: '695848555081',
    projectId: 'group-money-management-app',
    storageBucket: 'group-money-management-app.firebasestorage.app',
    iosBundleId: 'com.example.groupMoneyManagementApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnXmN4qvN-5dGFunOC4iDc5zzhIYu25Dc',
    appId: '1:695848555081:web:628050fb5ef5a7b8cfa598',
    messagingSenderId: '695848555081',
    projectId: 'group-money-management-app',
    authDomain: 'group-money-management-app.firebaseapp.com',
    storageBucket: 'group-money-management-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeLUcelBFR6fbaLXOyGL8t-FhfdGTzvJQ',
    appId: '1:695848555081:ios:97211f408de3f195cfa598',
    messagingSenderId: '695848555081',
    projectId: 'group-money-management-app',
    storageBucket: 'group-money-management-app.firebasestorage.app',
    iosBundleId: 'com.example.groupMoneyManagementApp',
  );

}